stages:
  - tests
  - quality

unittest_stage:
  stage: tests
  image: alpine:3.10
  variables:
    LBN_OUTPUT_FILENAME: /tmp/.htaccess
  before_script:
    - apk add -U --no-cache python3
    - pip3 install -U pip wheel
    - pip3 install jinja2
    - printenv
  script:
    - cd $CI_PROJECT_DIR/exercices/exercice-11 && python3 -m unittest test_generate_htaccess
  allow_failure: true

quality_stage:
  stage: quality
  image: alpine:3.10
  before_script:
    - apk add -U --no-cache python3
    - pip3 install -U pip wheel
    - pip3 install jinja2 pycodestyle
  script:
    - cd $CI_PROJECT_DIR/exercices/exercice-11 && pycodestyle test_generate_htaccess.py
  